// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT
// Wails v3 bindings for backend.AppService
import {backend} from '../models';
import {config} from '../models';

export function AddFavorite(arg1:string,arg2:string):Promise<void>;

export function AddIssueComment(arg1:string,arg2:number,arg3:string):Promise<void>;

export function AddToGitignore(arg1:string,arg2:string):Promise<void>;

export function AddToQueue(arg1:number,arg2:string):Promise<backend.QueueItem>;

export function BrowseForAudioFile():Promise<string>;

export function BrowseForClaude():Promise<string>;

export function BrowseForCodex():Promise<string>;

export function BrowseForGemini():Promise<string>;

export function CheckForUpdates():Promise<backend.UpdateInfo>;

export function CheckGitHubCLI():Promise<string>;

export function CheckHealth():Promise<backend.HealthInfo>;

export function ClearDoneFromQueue(arg1:number):Promise<void>;

export function ClearQueue(arg1:number):Promise<void>;

export function CloseSession(arg1:number):Promise<void>;

export function CreateDirectory(arg1:string):Promise<string>;

export function CreateIssue(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<backend.Issue>;

export function CreateNamedWorktree(arg1:string,arg2:string,arg3:string):Promise<backend.WorktreeInfo>;

export function CreateSession(arg1:Array<string>,arg2:string,arg3:number,arg4:number,arg5:string):Promise<number>;

export function CreateWorktree(arg1:string,arg2:number,arg3:string):Promise<backend.WorktreeInfo>;

export function DetachTab(arg1:string,arg2:string):Promise<[string, Error]>;

export function DetectClaudePath():Promise<backend.ClaudeDetectResult>;

export function DetectCodexPath():Promise<backend.CodexDetectResult>;

export function DetectGeminiPath():Promise<backend.GeminiDetectResult>;

export function DisableLogging():Promise<void>;

export function EnableLogging(arg1:boolean):Promise<string>;

export function GetAppVersion():Promise<string>;

export function CommitStaged(arg1:string,arg2:string):Promise<void>;

export function GenerateCommitSuggestion(arg1:string,arg2:Array<string>):Promise<backend.CommitSuggestion>;

export function GetConfig():Promise<config.Config>;

export function GetDiffStats(arg1:string):Promise<Array<backend.DiffFileStat>>;

export function GetFavorites(arg1:string):Promise<Array<string>>;

export function GetFileDiff(arg1:string,arg2:string):Promise<string>;

export function GetGitBranch(arg1:string):Promise<string>;

export function GetGitFileStatuses(arg1:string):Promise<Record<string, string>>;

export function GetGlobalLastActivityUnix():Promise<number>;

export function GetIssueDetail(arg1:string,arg2:number):Promise<backend.IssueDetail>;

export function GetIssueLabels(arg1:string):Promise<Array<backend.IssueLabel>>;

export function GetIssues(arg1:string,arg2:string):Promise<Array<backend.Issue>>;

export function GetLastCommitHash(arg1:string):Promise<string>;

export function GetLastCommitDiff(arg1:string):Promise<string>;

export function GetLastCommitTime(arg1:string):Promise<number>;

export function GetLocalBranches(arg1:string):Promise<Array<string>>;

export function GetLogPath():Promise<string>;

export function GetMergeConflicts(arg1:string):Promise<backend.MergeConflictInfo>;

export function GetOpenWindows():Promise<Array<{id: string, tabIds: string[]}>>;

export function GetOrCreateIssueBranch(arg1:string,arg2:number,arg3:string):Promise<string>;

export function GetQueue(arg1:number):Promise<Array<backend.QueueItem>>;

export function GetResolvedClaudePath():Promise<string>;

export function GetStatusLineStatus():Promise<backend.StatusLineStatus>;

export function GetResolvedCodexPath():Promise<string>;

export function GetResolvedGeminiPath():Promise<string>;

export function GetSessionIssue(arg1:number):Promise<number>;

export function GetWorkingDir():Promise<string>;

export function HasCleanWorkingTree(arg1:string):Promise<boolean>;

export function IsClaudeDetected():Promise<boolean>;

export function IsCodexDetected():Promise<boolean>;

export function IsGeminiDetected():Promise<boolean>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function IsOnIssueBranch(arg1:string,arg2:number):Promise<backend.IssueBranchInfo>;

export function LinkSessionIssue(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ListAllWorktrees(arg1:string):Promise<Array<backend.WorktreeInfo>>;

export function ListDirectory(arg1:string):Promise<Array<backend.FileEntry>>;

export function ListWorktrees(arg1:string):Promise<Array<backend.WorktreeInfo>>;

export function MergeWindowToMain(arg1:string,arg2:string):Promise<void>;

export function LoadTabs():Promise<config.SessionState>;

export function OpenDashboardWindow():Promise<string>;

export function OpenDirectory(arg1:string):Promise<string>;

export function OpenFileInEditor(arg1:string):Promise<string>;

export function OpenLogDir():Promise<void>;

export function PushBranch(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<backend.FileContent>;

export function RemoveFavorite(arg1:string,arg2:string):Promise<void>;

export function RemoveFromQueue(arg1:number,arg2:number):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:number):Promise<void>;

export function ResizeSession(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveTabs(arg1:config.SessionState):Promise<void>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<backend.FileEntry>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function StageFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateIssue(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ValidateClaudePath(arg1:string):Promise<boolean>;

export function ValidateCodexPath(arg1:string):Promise<boolean>;

export function ValidateGeminiPath(arg1:string):Promise<boolean>;

export function WriteToSession(arg1:number,arg2:string):Promise<void>;

// --- Sprint 1: Skills & Project ---

export function GetAllSkills():Promise<Array<backend.SkillInfo>>;

export function DetectProjectSkills(arg1:string):Promise<Array<string>>;

export function GetActiveSkills(arg1:string):Promise<Array<string>>;

export function InitProject(arg1:string,arg2:Array<string>):Promise<backend.ProjectInitResult>;

export function UpdateProjectSkills(arg1:string,arg2:Array<string>):Promise<backend.ProjectInitResult>;

export function IsProjectInitialized(arg1:string):Promise<boolean>;

// --- Sprint 2: Dashboard & Kanban ---

export function GetDashboardStats():Promise<backend.DashboardStats>;

export function GetKanbanState(arg1:string):Promise<backend.KanbanState>;

export function SaveKanbanState(arg1:string,arg2:backend.KanbanState):Promise<void>;

export function MoveKanbanCard(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddKanbanCard(arg1:string,arg2:backend.KanbanCard):Promise<backend.KanbanCard>;

export function RemoveKanbanCard(arg1:string,arg2:string):Promise<void>;

export function SyncKanbanWithIssues(arg1:string):Promise<backend.KanbanState>;

export function GeneratePlan(arg1:string,arg2:Array<string>):Promise<backend.Plan>;

export function GetPlans(arg1:string):Promise<Array<backend.Plan>>;

export function ApprovePlan(arg1:string,arg2:string):Promise<void>;

export function CancelPlan(arg1:string,arg2:string):Promise<void>;

export function DeletePlan(arg1:string,arg2:string):Promise<void>;

export function UpdatePlanStep(arg1:string,arg2:string,arg3:backend.PlanStep):Promise<void>;

export function CreateSchedule(arg1:string,arg2:backend.ScheduledTask):Promise<backend.ScheduledTask>;

export function GetSchedules(arg1:string):Promise<Array<backend.ScheduledTask>>;

export function UpdateSchedule(arg1:string,arg2:backend.ScheduledTask):Promise<void>;

export function DeleteSchedule(arg1:string,arg2:string):Promise<void>;

export function ToggleSchedule(arg1:string,arg2:string):Promise<void>;

// --- Sprint 3: Chat & Queue ---

export function CreateConversation(arg1:string,arg2:string,arg3:string):Promise<backend.Conversation>;

export function GetConversations(arg1:string):Promise<Array<backend.Conversation>>;

export function GetConversation(arg1:string,arg2:string):Promise<backend.Conversation>;

export function DeleteConversation(arg1:string,arg2:string):Promise<void>;

export function AddChatMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameConversation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAllQueues():Promise<Array<backend.QueueOverviewItem>>;

// --- Sprint 4: Orchestrator & Ask-User ---

export function ExecutePlan(arg1:string,arg2:string):Promise<void>;

export function StopPlan(arg1:string,arg2:string):Promise<void>;

export function CheckAskUser(arg1:number):Promise<backend.AskUserQuestion>;

export function AnswerAskUser(arg1:number,arg2:string):Promise<void>;

export function DismissAskUser(arg1:number):Promise<void>;
