// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIssueComment(arg1, arg2, arg3) {
  return window['go']['backend']['App']['AddIssueComment'](arg1, arg2, arg3);
}

export function AddToQueue(arg1, arg2) {
  return window['go']['backend']['App']['AddToQueue'](arg1, arg2);
}

export function BrowseForClaude() {
  return window['go']['backend']['App']['BrowseForClaude']();
}

export function CheckForUpdates() {
  return window['go']['backend']['App']['CheckForUpdates']();
}

export function CheckGitHubCLI() {
  return window['go']['backend']['App']['CheckGitHubCLI']();
}

export function CheckHealth() {
  return window['go']['backend']['App']['CheckHealth']();
}

export function ClearDoneFromQueue(arg1) {
  return window['go']['backend']['App']['ClearDoneFromQueue'](arg1);
}

export function ClearQueue(arg1) {
  return window['go']['backend']['App']['ClearQueue'](arg1);
}

export function CloseSession(arg1) {
  return window['go']['backend']['App']['CloseSession'](arg1);
}

export function CreateDirectory(arg1) {
  return window['go']['backend']['App']['CreateDirectory'](arg1);
}

export function DetectClaudePath() {
  return window['go']['backend']['App']['DetectClaudePath']();
}

export function CreateIssue(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateIssue'](arg1, arg2, arg3, arg4);
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function CreateWorktree(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateWorktree'](arg1, arg2, arg3);
}

export function DisableLogging() {
  return window['go']['backend']['App']['DisableLogging']();
}

export function EnableLogging(arg1) {
  return window['go']['backend']['App']['EnableLogging'](arg1);
}

export function GetAppVersion() {
  return window['go']['backend']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetResolvedClaudePath() {
  return window['go']['backend']['App']['GetResolvedClaudePath']();
}

export function GetGitBranch(arg1) {
  return window['go']['backend']['App']['GetGitBranch'](arg1);
}

export function GetGitFileStatuses(arg1) {
  return window['go']['backend']['App']['GetGitFileStatuses'](arg1);
}

export function GetIssueDetail(arg1, arg2) {
  return window['go']['backend']['App']['GetIssueDetail'](arg1, arg2);
}

export function GetIssueLabels(arg1) {
  return window['go']['backend']['App']['GetIssueLabels'](arg1);
}

export function GetIssues(arg1, arg2) {
  return window['go']['backend']['App']['GetIssues'](arg1, arg2);
}

export function GetLastCommitTime(arg1) {
  return window['go']['backend']['App']['GetLastCommitTime'](arg1);
}

export function GetLogPath() {
  return window['go']['backend']['App']['GetLogPath']();
}

export function GetOrCreateIssueBranch(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetOrCreateIssueBranch'](arg1, arg2, arg3);
}

export function GetQueue(arg1) {
  return window['go']['backend']['App']['GetQueue'](arg1);
}

export function GetSessionIssue(arg1) {
  return window['go']['backend']['App']['GetSessionIssue'](arg1);
}

export function GetWorkingDir() {
  return window['go']['backend']['App']['GetWorkingDir']();
}

export function HasCleanWorkingTree(arg1) {
  return window['go']['backend']['App']['HasCleanWorkingTree'](arg1);
}

export function IsClaudeDetected() {
  return window['go']['backend']['App']['IsClaudeDetected']();
}

export function IsGitRepo(arg1) {
  return window['go']['backend']['App']['IsGitRepo'](arg1);
}

export function LinkSessionIssue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['LinkSessionIssue'](arg1, arg2, arg3, arg4, arg5);
}

export function ListDirectory(arg1) {
  return window['go']['backend']['App']['ListDirectory'](arg1);
}

export function ListWorktrees(arg1) {
  return window['go']['backend']['App']['ListWorktrees'](arg1);
}

export function LoadTabs() {
  return window['go']['backend']['App']['LoadTabs']();
}

export function RemoveFromQueue(arg1, arg2) {
  return window['go']['backend']['App']['RemoveFromQueue'](arg1, arg2);
}

export function RemoveWorktree(arg1, arg2) {
  return window['go']['backend']['App']['RemoveWorktree'](arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SaveTabs(arg1) {
  return window['go']['backend']['App']['SaveTabs'](arg1);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['backend']['App']['SearchFiles'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}

export function SendNotification(arg1, arg2) {
  return window['go']['backend']['App']['SendNotification'](arg1, arg2);
}

export function UpdateIssue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateIssue'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateClaudePath(arg1) {
  return window['go']['backend']['App']['ValidateClaudePath'](arg1);
}

export function WriteToSession(arg1, arg2) {
  return window['go']['backend']['App']['WriteToSession'](arg1, arg2);
}
