// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT
// Wails v3 bindings for backend.AppService
// Method IDs computed via FNV-1a hash of fully-qualified name:
// "github.com/patrick-goecommerce/Multiterminal-UI/internal/backend.AppService.<Method>"

import { Call as $Call, Create as $Create } from '/wails/runtime.js';

export function AddFavorite(arg1, arg2) {
  return $Call.ByID(2606846158, arg1, arg2);
}

export function AddIssueComment(arg1, arg2, arg3) {
  return $Call.ByID(3658299714, arg1, arg2, arg3);
}

export function AddToGitignore(arg1, arg2) {
  return $Call.ByID(3593643739, arg1, arg2);
}

export function AddToQueue(arg1, arg2) {
  return $Call.ByID(1175419502, arg1, arg2);
}

export function BrowseForAudioFile() {
  return $Call.ByID(960558084);
}

export function BrowseForClaude() {
  return $Call.ByID(1995003730);
}

export function BrowseForCodex() {
  return $Call.ByID(2919136575);
}

export function BrowseForGemini() {
  return $Call.ByID(1027700551);
}

export function CheckForUpdates() {
  return $Call.ByID(3663542522);
}

export function CheckGitHubCLI() {
  return $Call.ByID(2375732200);
}

export function CheckHealth() {
  return $Call.ByID(3622525547);
}

export function ClearDoneFromQueue(arg1) {
  return $Call.ByID(1710540151, arg1);
}

export function ClearQueue(arg1) {
  return $Call.ByID(990141303, arg1);
}

export function CloseSession(arg1) {
  return $Call.ByID(961833007, arg1);
}

export function CommitStaged(arg1, arg2) {
  return $Call.ByID(3916022276, arg1, arg2);
}

export function CreateDirectory(arg1) {
  return $Call.ByID(3107327782, arg1);
}

export function CreateIssue(arg1, arg2, arg3, arg4) {
  return $Call.ByID(2241721278, arg1, arg2, arg3, arg4);
}

export function CreateNamedWorktree(arg1, arg2, arg3) {
  return $Call.ByID(1740508309, arg1, arg2, arg3);
}

export function CreateSession(arg1, arg2, arg3, arg4, arg5) {
  return $Call.ByID(1395065, arg1, arg2, arg3, arg4, arg5);
}

export function CreateWorktree(arg1, arg2, arg3) {
  return $Call.ByID(51192822, arg1, arg2, arg3);
}

export function DetachTab(arg1, arg2, arg3) {
  return $Call.ByID(3406932983, arg1, arg2, arg3);
}

export function GetDetachedTabState(arg1) {
  return $Call.ByID(3336299475, arg1);
}

export function DetectClaudePath() {
  return $Call.ByID(3544275289);
}

export function DetectCodexPath() {
  return $Call.ByID(3451434784);
}

export function DetectGeminiPath() {
  return $Call.ByID(3042203720);
}

export function DisableLogging() {
  return $Call.ByID(2666137690);
}

export function EnableLogging(arg1) {
  return $Call.ByID(2270560969, arg1);
}

export function GenerateCommitSuggestion(arg1, arg2) {
  return $Call.ByID(4184172341, arg1, arg2);
}

export function GetAppVersion() {
  return $Call.ByID(1351953244);
}

export function GetConfig() {
  return $Call.ByID(741379475);
}

export function GetDiffStats(arg1) {
  return $Call.ByID(2590445749, arg1);
}

export function GetFavorites(arg1) {
  return $Call.ByID(508786262, arg1);
}

export function GetFileDiff(arg1, arg2) {
  return $Call.ByID(1856212252, arg1, arg2);
}

export function GetGitBranch(arg1) {
  return $Call.ByID(3609051727, arg1);
}

export function GetGitFileStatuses(arg1) {
  return $Call.ByID(1919900195, arg1);
}

export function GetGlobalLastActivityUnix() {
  return $Call.ByID(593134621);
}

export function GetIssueDetail(arg1, arg2) {
  return $Call.ByID(220592869, arg1, arg2);
}

export function GetIssueLabels(arg1) {
  return $Call.ByID(3613778195, arg1);
}

export function GetIssues(arg1, arg2) {
  return $Call.ByID(2569602789, arg1, arg2);
}

export function GetLastCommitHash(arg1) {
  return $Call.ByID(1429232572, arg1);
}

export function GetLastCommitDiff(arg1) {
  return $Call.ByID(4144005451, arg1);
}

export function GetLastCommitTime(arg1) {
  return $Call.ByID(3366753469, arg1);
}

export function GetLocalBranches(arg1) {
  return $Call.ByID(2816100456, arg1);
}

export function GetLogPath() {
  return $Call.ByID(1817158190);
}

export function GetMergeConflicts(arg1) {
  return $Call.ByID(3682275398, arg1);
}

export function GetOpenWindows() {
  return $Call.ByID(678709378);
}

export function GetOrCreateIssueBranch(arg1, arg2, arg3) {
  return $Call.ByID(3998065247, arg1, arg2, arg3);
}

export function GetQueue(arg1) {
  return $Call.ByID(2075083900, arg1);
}

export function GetResolvedClaudePath() {
  return $Call.ByID(2078339156);
}

export function GetStatusLineStatus() {
  return $Call.ByID(1969813307);
}

export function GetResolvedCodexPath() {
  return $Call.ByID(3436116343);
}

export function GetResolvedGeminiPath() {
  return $Call.ByID(1942354009);
}

export function GetSessionIssue(arg1) {
  return $Call.ByID(2723699338, arg1);
}

export function GetWorkingDir() {
  return $Call.ByID(1361852195);
}

export function HasCleanWorkingTree(arg1) {
  return $Call.ByID(418806789, arg1);
}

export function IsClaudeDetected() {
  return $Call.ByID(434809535);
}

export function IsCodexDetected() {
  return $Call.ByID(1539261952);
}

export function IsGeminiDetected() {
  return $Call.ByID(864734474);
}

export function IsGitRepo(arg1) {
  return $Call.ByID(1513281313, arg1);
}

export function IsOnIssueBranch(arg1, arg2) {
  return $Call.ByID(2587428749, arg1, arg2);
}

export function LinkSessionIssue(arg1, arg2, arg3, arg4, arg5) {
  return $Call.ByID(563592256, arg1, arg2, arg3, arg4, arg5);
}

export function ListAllWorktrees(arg1) {
  return $Call.ByID(824490512, arg1);
}

export function ListDirectory(arg1) {
  return $Call.ByID(1894045958, arg1);
}

export function ListWorktrees(arg1) {
  return $Call.ByID(1397013567, arg1);
}

export function MergeWindowToMain(arg1, arg2) {
  return $Call.ByID(1541318433, arg1, arg2);
}

export function LoadTabs() {
  return $Call.ByID(542856639);
}

export function OpenFileInEditor(arg1) {
  return $Call.ByID(386585087, arg1);
}

export function OpenLogDir() {
  return $Call.ByID(1351486042);
}

export function PushBranch(arg1) {
  return $Call.ByID(3236885099, arg1);
}

export function ReadFile(arg1) {
  return $Call.ByID(1041447045, arg1);
}

export function RemoveFavorite(arg1, arg2) {
  return $Call.ByID(3960346899, arg1, arg2);
}

export function RemoveFromQueue(arg1, arg2) {
  return $Call.ByID(1770424462, arg1, arg2);
}

export function RemoveWorktree(arg1, arg2) {
  return $Call.ByID(375711242, arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
  return $Call.ByID(3357609161, arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return $Call.ByID(2393674620, arg1);
}

export function SaveWindowTabs(arg1, arg2) {
  return $Call.ByID(1191563946, arg1, arg2);
}

export function SetDraggingTab(arg1, arg2, arg3) {
  return $Call.ByID(3912872371, arg1, arg2, arg3);
}

export function ClaimDraggedTab(arg1) {
  return $Call.ByID(3555450600, arg1);
}

export function ClearDraggingTab() {
  return $Call.ByID(1716946648);
}

export function SaveTabs(arg1) {
  return $Call.ByID(3270785638, arg1);
}

export function SearchFiles(arg1, arg2) {
  return $Call.ByID(4086168286, arg1, arg2);
}

export function SelectDirectory(arg1) {
  return $Call.ByID(1609319006, arg1);
}

export function SendNotification(arg1, arg2) {
  return $Call.ByID(855829018, arg1, arg2);
}

export function StageFiles(arg1, arg2) {
  return $Call.ByID(2458453226, arg1, arg2);
}

export function UpdateIssue(arg1, arg2, arg3, arg4, arg5) {
  return $Call.ByID(3829405869, arg1, arg2, arg3, arg4, arg5);
}

export function ValidateClaudePath(arg1) {
  return $Call.ByID(688761244, arg1);
}

export function ValidateCodexPath(arg1) {
  return $Call.ByID(1225856159, arg1);
}

export function ValidateGeminiPath(arg1) {
  return $Call.ByID(931204881, arg1);
}

export function WriteToSession(arg1, arg2) {
  return $Call.ByID(2058166105, arg1, arg2);
}

// --- Sprint 1: Skills & Project ---

export function GetAllSkills() {
  return $Call.ByID(185667762);
}

export function DetectProjectSkills(arg1) {
  return $Call.ByID(1259502175, arg1);
}

export function GetActiveSkills(arg1) {
  return $Call.ByID(2895186329, arg1);
}

export function InitProject(arg1, arg2) {
  return $Call.ByID(2249000730, arg1, arg2);
}

export function UpdateProjectSkills(arg1, arg2) {
  return $Call.ByID(18054413, arg1, arg2);
}

export function IsProjectInitialized(arg1) {
  return $Call.ByID(3139499694, arg1);
}

// --- Sprint 2: Dashboard & Kanban ---

export function GetDashboardStats() {
  return $Call.ByID(686669050);
}

export function GetKanbanState(arg1) {
  return $Call.ByID(79316911, arg1);
}

export function SaveKanbanState(arg1, arg2) {
  return $Call.ByID(4252869218, arg1, arg2);
}

export function MoveKanbanCard(arg1, arg2, arg3, arg4) {
  return $Call.ByID(2892390087, arg1, arg2, arg3, arg4);
}

export function AddKanbanCard(arg1, arg2) {
  return $Call.ByID(2966990003, arg1, arg2);
}

export function RemoveKanbanCard(arg1, arg2) {
  return $Call.ByID(3626901330, arg1, arg2);
}

export function SyncKanbanWithIssues(arg1) {
  return $Call.ByID(146449503, arg1);
}

export function GeneratePlan(arg1, arg2) {
  return $Call.ByID(716985523, arg1, arg2);
}

export function GetPlans(arg1) {
  return $Call.ByID(1106968791, arg1);
}

export function ApprovePlan(arg1, arg2) {
  return $Call.ByID(195422847, arg1, arg2);
}

export function CancelPlan(arg1, arg2) {
  return $Call.ByID(797937358, arg1, arg2);
}

export function DeletePlan(arg1, arg2) {
  return $Call.ByID(2632421671, arg1, arg2);
}

export function UpdatePlanStep(arg1, arg2, arg3) {
  return $Call.ByID(3495455239, arg1, arg2, arg3);
}

export function CreateSchedule(arg1, arg2) {
  return $Call.ByID(1879309326, arg1, arg2);
}

export function GetSchedules(arg1) {
  return $Call.ByID(2525528361, arg1);
}

export function UpdateSchedule(arg1, arg2) {
  return $Call.ByID(986255363, arg1, arg2);
}

export function DeleteSchedule(arg1, arg2) {
  return $Call.ByID(3346650489, arg1, arg2);
}

export function ToggleSchedule(arg1, arg2) {
  return $Call.ByID(4210589378, arg1, arg2);
}
