// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {config} from '../models';

export function AddIssueComment(arg1:string,arg2:number,arg3:string):Promise<void>;

export function AddToQueue(arg1:number,arg2:string):Promise<backend.QueueItem>;

export function BrowseForClaude():Promise<string>;

export function CheckForUpdates():Promise<backend.UpdateInfo>;

export function CheckGitHubCLI():Promise<string>;

export function CheckHealth():Promise<backend.HealthInfo>;

export function ClearDoneFromQueue(arg1:number):Promise<void>;

export function ClearQueue(arg1:number):Promise<void>;

export function CloseSession(arg1:number):Promise<void>;

export function CreateDirectory(arg1:string):Promise<string>;

export function CreateIssue(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<backend.Issue>;

export function CreateSession(arg1:Array<string>,arg2:string,arg3:number,arg4:number):Promise<number>;

export function CreateWorktree(arg1:string,arg2:number,arg3:string):Promise<backend.WorktreeInfo>;

export function DetectClaudePath():Promise<backend.ClaudeDetectResult>;

export function DisableLogging():Promise<void>;

export function EnableLogging(arg1:boolean):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetGitBranch(arg1:string):Promise<string>;

export function GetGitFileStatuses(arg1:string):Promise<Record<string, string>>;

export function GetIssueDetail(arg1:string,arg2:number):Promise<backend.IssueDetail>;

export function GetIssueLabels(arg1:string):Promise<Array<backend.IssueLabel>>;

export function GetIssues(arg1:string,arg2:string):Promise<Array<backend.Issue>>;

export function GetLastCommitTime(arg1:string):Promise<number>;

export function GetLogPath():Promise<string>;

export function GetOrCreateIssueBranch(arg1:string,arg2:number,arg3:string):Promise<string>;

export function GetQueue(arg1:number):Promise<Array<backend.QueueItem>>;

export function GetResolvedClaudePath():Promise<string>;

export function GetSessionIssue(arg1:number):Promise<number>;

export function GetWorkingDir():Promise<string>;

export function HasCleanWorkingTree(arg1:string):Promise<boolean>;

export function IsClaudeDetected():Promise<boolean>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function LinkSessionIssue(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ListDirectory(arg1:string):Promise<Array<backend.FileEntry>>;

export function ListWorktrees(arg1:string):Promise<Array<backend.WorktreeInfo>>;

export function LoadTabs():Promise<config.SessionState>;

export function RemoveFromQueue(arg1:number,arg2:number):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:number):Promise<void>;

export function ResizeSession(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveTabs(arg1:config.SessionState):Promise<void>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<backend.FileEntry>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function UpdateIssue(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ValidateClaudePath(arg1:string):Promise<boolean>;

export function WriteToSession(arg1:number,arg2:string):Promise<void>;
