// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AudioSettings holds audio feedback configuration.
 */
export class AudioSettings {
    /**
     * Creates a new AudioSettings instance.
     * @param {Partial<AudioSettings>} [$$source = {}] - The source object to create the AudioSettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["enabled"] = null;
        }
        if (!("volume" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["volume"] = 0;
        }
        if (!("when_focused" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["when_focused"] = null;
        }
        if (!("done_sound" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["done_sound"] = "";
        }
        if (!("input_sound" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input_sound"] = "";
        }
        if (!("error_sound" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error_sound"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AudioSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AudioSettings(/** @type {Partial<AudioSettings>} */($$parsedSource));
    }
}

/**
 * CommandEntry represents a user-defined command in the command palette.
 */
export class CommandEntry {
    /**
     * Creates a new CommandEntry instance.
     * @param {Partial<CommandEntry>} [$$source = {}] - The source object to create the CommandEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandEntry(/** @type {Partial<CommandEntry>} */($$parsedSource));
    }
}

/**
 * Config holds all user-configurable settings.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("default_shell" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default_shell"] = "";
        }
        if (!("default_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default_dir"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("terminal_color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminal_color"] = "";
        }
        if (!("max_panes_per_tab" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_panes_per_tab"] = 0;
        }
        if (!("sidebar_width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sidebar_width"] = 0;
        }
        if (!("claude_command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["claude_command"] = "";
        }
        if (!("claude_models" in $$source)) {
            /**
             * @member
             * @type {ModelEntry[]}
             */
            this["claude_models"] = [];
        }
        if (!("commit_reminder_minutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["commit_reminder_minutes"] = 0;
        }
        if (!("restore_session" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["restore_session"] = null;
        }
        if (!("logging_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["logging_enabled"] = false;
        }
        if (!("auto_branch_on_issue" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["auto_branch_on_issue"] = null;
        }
        if (!("issue_tracking" in $$source)) {
            /**
             * @member
             * @type {IssueTracking}
             */
            this["issue_tracking"] = (new IssueTracking());
        }
        if (!("commands" in $$source)) {
            /**
             * @member
             * @type {CommandEntry[]}
             */
            this["commands"] = [];
        }
        if (!("audio" in $$source)) {
            /**
             * @member
             * @type {AudioSettings}
             */
            this["audio"] = (new AudioSettings());
        }
        if (!("localhost_auto_open" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localhost_auto_open"] = "";
        }
        if (!("sidebar_pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sidebar_pinned"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] } | undefined}
             */
            this["favorites"] = undefined;
        }
        if (!("font_family" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["font_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType4;
        const $$createField14_0 = $$createType5;
        const $$createField17_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("claude_models" in $$parsedSource) {
            $$parsedSource["claude_models"] = $$createField7_0($$parsedSource["claude_models"]);
        }
        if ("issue_tracking" in $$parsedSource) {
            $$parsedSource["issue_tracking"] = $$createField12_0($$parsedSource["issue_tracking"]);
        }
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField13_0($$parsedSource["commands"]);
        }
        if ("audio" in $$parsedSource) {
            $$parsedSource["audio"] = $$createField14_0($$parsedSource["audio"]);
        }
        if ("favorites" in $$parsedSource) {
            $$parsedSource["favorites"] = $$createField17_0($$parsedSource["favorites"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * IssueTracking holds settings for automatic issue progress reporting.
 */
export class IssueTracking {
    /**
     * Creates a new IssueTracking instance.
     * @param {Partial<IssueTracking>} [$$source = {}] - The source object to create the IssueTracking.
     */
    constructor($$source = {}) {
        if (!("auto_comment_on_start" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_comment_on_start"] = false;
        }
        if (!("auto_comment_on_done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_comment_on_done"] = false;
        }
        if (!("auto_comment_on_close" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_comment_on_close"] = false;
        }
        if (!("auto_close_issue" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_close_issue"] = false;
        }
        if (!("include_cost_in_report" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["include_cost_in_report"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueTracking instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IssueTracking}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IssueTracking(/** @type {Partial<IssueTracking>} */($$parsedSource));
    }
}

/**
 * ModelEntry represents a selectable Claude model in the launch dialog.
 */
export class ModelEntry {
    /**
     * Creates a new ModelEntry instance.
     * @param {Partial<ModelEntry>} [$$source = {}] - The source object to create the ModelEntry.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelEntry(/** @type {Partial<ModelEntry>} */($$parsedSource));
    }
}

/**
 * SavedPane captures enough information to re-launch a single pane.
 */
export class SavedPane {
    /**
     * Creates a new SavedPane instance.
     * @param {Partial<SavedPane>} [$$source = {}] - The source object to create the SavedPane.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * maps to ui.PaneMode (0=shell, 1=claude, 2=yolo)
             * @member
             * @type {number}
             */
            this["mode"] = 0;
        }
        if (!("model" in $$source)) {
            /**
             * model label (empty for shell)
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * linked GitHub issue number
             * @member
             * @type {number | undefined}
             */
            this["issue_number"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * branch created for issue
             * @member
             * @type {string | undefined}
             */
            this["issue_branch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * per-pane font zoom offset
             * @member
             * @type {number | undefined}
             */
            this["zoom_delta"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedPane instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedPane}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedPane(/** @type {Partial<SavedPane>} */($$parsedSource));
    }
}

/**
 * SavedTab captures a single tab's layout.
 */
export class SavedTab {
    /**
     * Creates a new SavedTab instance.
     * @param {Partial<SavedTab>} [$$source = {}] - The source object to create the SavedTab.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("focus_idx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["focus_idx"] = 0;
        }
        if (!("panes" in $$source)) {
            /**
             * @member
             * @type {SavedPane[]}
             */
            this["panes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedTab instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedTab}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("panes" in $$parsedSource) {
            $$parsedSource["panes"] = $$createField3_0($$parsedSource["panes"]);
        }
        return new SavedTab(/** @type {Partial<SavedTab>} */($$parsedSource));
    }
}

/**
 * SessionState is the top-level structure serialised to disk.
 */
export class SessionState {
    /**
     * Creates a new SessionState instance.
     * @param {Partial<SessionState>} [$$source = {}] - The source object to create the SessionState.
     */
    constructor($$source = {}) {
        if (!("active_tab" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active_tab"] = 0;
        }
        if (!("tabs" in $$source)) {
            /**
             * @member
             * @type {SavedTab[]}
             */
            this["tabs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField1_0($$parsedSource["tabs"]);
        }
        return new SessionState(/** @type {Partial<SessionState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ModelEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = IssueTracking.createFrom;
const $$createType3 = CommandEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = AudioSettings.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = SavedPane.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = SavedTab.createFrom;
const $$createType11 = $Create.Array($$createType10);
