// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the main Wails application struct. All exported methods are
 * automatically available to the frontend via generated TypeScript bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFavorite adds a path to the favorites for the given directory
 * and persists the config to disk.
 * @param {string} dir
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function AddFavorite(dir, path) {
    return $Call.ByID(2606846158, dir, path);
}

/**
 * AddIssueComment adds a comment to an existing issue.
 * @param {string} dir
 * @param {number} $number
 * @param {string} body
 * @returns {$CancellablePromise<void>}
 */
export function AddIssueComment(dir, $number, body) {
    return $Call.ByID(3658299714, dir, $number, body);
}

/**
 * AddToGitignore appends relPath to the .gitignore at the repo root of dir.
 * Creates .gitignore if it does not exist. No-ops if the entry is already present.
 * relPath must be relative to the repo root (forward slashes preferred; backslashes are normalized).
 * @param {string} dir
 * @param {string} relPath
 * @returns {$CancellablePromise<void>}
 */
export function AddToGitignore(dir, relPath) {
    return $Call.ByID(3593643739, dir, relPath);
}

/**
 * AddToQueue adds a prompt to a session's pipeline queue.
 * If the session is idle/done and nothing is in-flight, it triggers immediately.
 * @param {number} sessionId
 * @param {string} prompt
 * @returns {$CancellablePromise<$models.QueueItem>}
 */
export function AddToQueue(sessionId, prompt) {
    return $Call.ByID(1175419502, sessionId, prompt).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BrowseForAudioFile opens a native file picker for audio files.
 * @returns {$CancellablePromise<string>}
 */
export function BrowseForAudioFile() {
    return $Call.ByID(960558084);
}

/**
 * BrowseForClaude opens a native file picker filtered for executables.
 * @returns {$CancellablePromise<string>}
 */
export function BrowseForClaude() {
    return $Call.ByID(1995003730);
}

/**
 * CheckForUpdates queries the GitHub releases API and compares the latest
 * release tag with the current version.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdates() {
    return $Call.ByID(3663542522).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckGitHubCLI checks if the gh CLI is installed and authenticated.
 * Returns "ok", "not_installed", or "not_authenticated".
 * @returns {$CancellablePromise<string>}
 */
export function CheckGitHubCLI() {
    return $Call.ByID(2375732200);
}

/**
 * CheckHealth returns the current health/logging state for the frontend.
 * @returns {$CancellablePromise<$models.HealthInfo>}
 */
export function CheckHealth() {
    return $Call.ByID(3622525547).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ClaimDraggedTab is called by the target window when a tab is dropped on its
 * tab bar. It returns the tab state JSON so the target can import the tab, and
 * emits window:tab-claimed so the source window removes the tab.
 * Returns empty string if nothing is being dragged (or wrong tabID).
 * @param {string} tabID
 * @returns {$CancellablePromise<string>}
 */
export function ClaimDraggedTab(tabID) {
    return $Call.ByID(3555450600, tabID);
}

/**
 * ClearDoneFromQueue removes all completed items from the queue.
 * @param {number} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function ClearDoneFromQueue(sessionId) {
    return $Call.ByID(1710540151, sessionId);
}

/**
 * ClearDraggingTab is called when a drag ends without a cross-window drop.
 * @returns {$CancellablePromise<void>}
 */
export function ClearDraggingTab() {
    return $Call.ByID(1716946648);
}

/**
 * ClearQueue removes all items from a session's queue.
 * @param {number} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function ClearQueue(sessionId) {
    return $Call.ByID(990141303, sessionId);
}

/**
 * CloseSession terminates a session and removes it.
 * The session is closed asynchronously but removed from the map only
 * after Close() completes, ensuring streamOutput drains all buffered
 * data before the session is gone.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(id) {
    return $Call.ByID(961833007, id);
}

/**
 * CreateDirectory creates a new directory (including parents) and returns
 * an error string (empty on success).
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function CreateDirectory(path) {
    return $Call.ByID(3107327782, path);
}

/**
 * CreateIssue creates a new GitHub issue and returns it.
 * @param {string} dir
 * @param {string} title
 * @param {string} body
 * @param {string[]} labels
 * @returns {$CancellablePromise<$models.Issue | null>}
 */
export function CreateIssue(dir, title, body, labels) {
    return $Call.ByID(2241721278, dir, title, body, labels).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * CreateNamedWorktree creates a general-purpose worktree not tied to an issue.
 * name is a display name, baseBranch is the branch to fork from.
 * Creates at .mt-worktrees/<sanitized-name>/ with branch "terminal/<sanitized-name>".
 * @param {string} dir
 * @param {string} name
 * @param {string} baseBranch
 * @returns {$CancellablePromise<$models.WorktreeInfo | null>}
 */
export function CreateNamedWorktree(dir, name, baseBranch) {
    return $Call.ByID(1740508309, dir, name, baseBranch).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * CreateSession spawns a new PTY session and starts streaming its output
 * to the frontend. Returns the session ID.
 * mode must be "shell", "claude", or "claude-yolo"; it controls env injection.
 * @param {string[]} argv
 * @param {string} dir
 * @param {number} rows
 * @param {number} cols
 * @param {string} mode
 * @returns {$CancellablePromise<number>}
 */
export function CreateSession(argv, dir, rows, cols, mode) {
    return $Call.ByID(1395065, argv, dir, rows, cols, mode);
}

/**
 * CreateWorktree creates a git worktree for an issue with its own branch.
 * Returns the worktree path and branch name.
 * @param {string} dir
 * @param {number} issueNumber
 * @param {string} title
 * @returns {$CancellablePromise<$models.WorktreeInfo | null>}
 */
export function CreateWorktree(dir, issueNumber, title) {
    return $Call.ByID(51192822, dir, issueNumber, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * DetachTab creates a new Wails window for the given tab.
 * tabStateJSON is the serialised tab object from the frontend store; it is
 * stored temporarily so the new window can retrieve it via GetDetachedTabState.
 * Returns the new window ID.
 * @param {string} tabID
 * @param {string} sourceWindowID
 * @param {string} tabStateJSON
 * @returns {$CancellablePromise<string>}
 */
export function DetachTab(tabID, sourceWindowID, tabStateJSON) {
    return $Call.ByID(3406932983, tabID, sourceWindowID, tabStateJSON);
}

/**
 * DetectClaudePath tries to locate the Claude CLI binary.
 * Priority: absolute config path → PATH lookup → known install locations.
 * @returns {$CancellablePromise<$models.ClaudeDetectResult>}
 */
export function DetectClaudePath() {
    return $Call.ByID(3544275289).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DisableLogging deactivates file logging and resets to stderr.
 * @returns {$CancellablePromise<void>}
 */
export function DisableLogging() {
    return $Call.ByID(2666137690);
}

/**
 * EnableLogging activates file logging. If auto is true, it was triggered
 * by crash detection and will auto-disable after 3 clean shutdowns.
 * @param {boolean} auto
 * @returns {$CancellablePromise<string>}
 */
export function EnableLogging(auto) {
    return $Call.ByID(2270560969, auto);
}

/**
 * GetAppVersion returns the current application version string.
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(1351953244);
}

/**
 * GetConfig returns the current application configuration.
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(741379475).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetDetachedTabState returns and clears the serialised tab state stored for
 * the given window ID during DetachTab. Returns empty string if not found.
 * @param {string} windowID
 * @returns {$CancellablePromise<string>}
 */
export function GetDetachedTabState(windowID) {
    return $Call.ByID(3336299475, windowID);
}

/**
 * GetFavorites returns the list of favorite paths for the given directory.
 * @param {string} dir
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFavorites(dir) {
    return $Call.ByID(508786262, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetGitBranch returns the current git branch for the given directory.
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function GetGitBranch(dir) {
    return $Call.ByID(3609051727, dir);
}

/**
 * GetGitFileStatuses returns a map of relative file paths to their git status
 * for the given directory. Uses `git status --porcelain` for parsing.
 * @param {string} dir
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetGitFileStatuses(dir) {
    return $Call.ByID(1919900195, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetIssueDetail returns the full details of a single issue including comments.
 * @param {string} dir
 * @param {number} $number
 * @returns {$CancellablePromise<$models.IssueDetail | null>}
 */
export function GetIssueDetail(dir, $number) {
    return $Call.ByID(220592869, dir, $number).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetIssueLabels returns all available labels for the repo in dir.
 * @param {string} dir
 * @returns {$CancellablePromise<$models.IssueLabel[]>}
 */
export function GetIssueLabels(dir) {
    return $Call.ByID(3613778195, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetIssues returns a list of GitHub issues for the repo in dir.
 * state can be "open", "closed", or "all".
 * @param {string} dir
 * @param {string} state
 * @returns {$CancellablePromise<$models.Issue[]>}
 */
export function GetIssues(dir, state) {
    return $Call.ByID(2569602789, dir, state).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetLastCommitTime returns the Unix timestamp (seconds) of the last git commit.
 * @param {string} dir
 * @returns {$CancellablePromise<number>}
 */
export function GetLastCommitTime(dir) {
    return $Call.ByID(3366753469, dir);
}

/**
 * GetLocalBranches returns local branch names for the repo containing dir.
 * @param {string} dir
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLocalBranches(dir) {
    return $Call.ByID(2816100456, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetLogPath returns the current log file path.
 * @returns {$CancellablePromise<string>}
 */
export function GetLogPath() {
    return $Call.ByID(1817158190);
}

/**
 * GetMergeConflicts returns conflict information for the given directory.
 * @param {string} dir
 * @returns {$CancellablePromise<$models.MergeConflictInfo>}
 */
export function GetMergeConflicts(dir) {
    return $Call.ByID(3682275398, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetOpenWindows returns info about all open windows.
 * @returns {$CancellablePromise<$models.WindowInfo[]>}
 */
export function GetOpenWindows() {
    return $Call.ByID(678709378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetOrCreateIssueBranch checks if an issue branch exists, creates it if not,
 * and switches to it. Returns the branch name or an error.
 * If the working tree is dirty, it returns an error rather than risking data loss.
 * @param {string} dir
 * @param {number} $number
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function GetOrCreateIssueBranch(dir, $number, title) {
    return $Call.ByID(3998065247, dir, $number, title);
}

/**
 * GetQueue returns the current pipeline queue for a session.
 * @param {number} sessionId
 * @returns {$CancellablePromise<$models.QueueItem[]>}
 */
export function GetQueue(sessionId) {
    return $Call.ByID(2075083900, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetResolvedClaudePath returns the cached resolved path (set at startup).
 * @returns {$CancellablePromise<string>}
 */
export function GetResolvedClaudePath() {
    return $Call.ByID(2078339156);
}

/**
 * GetSessionIssue returns the issue number linked to a session, or 0.
 * @param {number} sessionID
 * @returns {$CancellablePromise<number>}
 */
export function GetSessionIssue(sessionID) {
    return $Call.ByID(2723699338, sessionID);
}

/**
 * GetWorkingDir returns the effective working directory (from config or cwd).
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkingDir() {
    return $Call.ByID(1361852195);
}

/**
 * HasCleanWorkingTree checks for uncommitted changes (exported for frontend).
 * @param {string} dir
 * @returns {$CancellablePromise<boolean>}
 */
export function HasCleanWorkingTree(dir) {
    return $Call.ByID(418806789, dir);
}

/**
 * IsClaudeDetected returns whether Claude CLI was found during detection.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsClaudeDetected() {
    return $Call.ByID(434809535);
}

/**
 * IsGitRepo checks if the given directory is a git repository (exported for frontend).
 * @param {string} dir
 * @returns {$CancellablePromise<boolean>}
 */
export function IsGitRepo(dir) {
    return $Call.ByID(1513281313, dir);
}

/**
 * IsOnIssueBranch checks if the current branch in dir is an issue branch.
 * targetIssue allows checking whether it's the same issue in one call.
 * @param {string} dir
 * @param {number} targetIssue
 * @returns {$CancellablePromise<$models.IssueBranchInfo>}
 */
export function IsOnIssueBranch(dir, targetIssue) {
    return $Call.ByID(2587428749, dir, targetIssue).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * LinkSessionIssue associates a GitHub issue with a session for tracking.
 * It also posts a "start" progress comment on the issue if configured.
 * @param {number} sessionID
 * @param {number} $number
 * @param {string} title
 * @param {string} branch
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function LinkSessionIssue(sessionID, $number, title, branch, dir) {
    return $Call.ByID(563592256, sessionID, $number, title, branch, dir);
}

/**
 * ListAllWorktrees returns ALL git worktrees categorized as "main", "terminal", or "issue".
 * @param {string} dir
 * @returns {$CancellablePromise<$models.WorktreeInfo[]>}
 */
export function ListAllWorktrees(dir) {
    return $Call.ByID(824490512, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * ListDirectory returns the contents of a directory, sorted dirs-first.
 * If dir is empty, it defaults to the current working directory.
 * @param {string} dir
 * @returns {$CancellablePromise<$models.FileEntry[]>}
 */
export function ListDirectory(dir) {
    return $Call.ByID(1894045958, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ListWorktrees returns all active worktrees that belong to Multiterminal.
 * @param {string} dir
 * @returns {$CancellablePromise<$models.WorktreeInfo[]>}
 */
export function ListWorktrees(dir) {
    return $Call.ByID(1397013567, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * LoadTabs returns the previously saved tab/pane layout, or nil.
 * @returns {$CancellablePromise<config$0.SessionState | null>}
 */
export function LoadTabs() {
    return $Call.ByID(542856639).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * MergeWindowToMain is kept for compatibility but is no longer the primary
 * merge path. The WindowClosing hook now handles the merge directly.
 * @param {string} windowID
 * @param {string} tabState
 * @returns {$CancellablePromise<void>}
 */
export function MergeWindowToMain(windowID, tabState) {
    return $Call.ByID(1541318433, windowID, tabState);
}

/**
 * OpenFileInEditor opens the file in the system default editor.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileInEditor(path) {
    return $Call.ByID(386585087, path);
}

/**
 * OpenLogDir opens the log directory in the system file explorer.
 * @returns {$CancellablePromise<void>}
 */
export function OpenLogDir() {
    return $Call.ByID(1351486042);
}

/**
 * ReadFile reads a file and returns its content for preview.
 * Files larger than 1 MB or detected as binary are rejected.
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileContent>}
 */
export function ReadFile(path) {
    return $Call.ByID(1041447045, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * RemoveFavorite removes a path from the favorites for the given directory
 * and persists the config to disk.
 * @param {string} dir
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFavorite(dir, path) {
    return $Call.ByID(3960346899, dir, path);
}

/**
 * RemoveFromQueue removes a single item by ID.
 * Items with status "sent" (currently executing) cannot be removed.
 * @param {number} sessionId
 * @param {number} itemId
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFromQueue(sessionId, itemId) {
    return $Call.ByID(1770424462, sessionId, itemId);
}

/**
 * RemoveWorktree removes a worktree for an issue and optionally its branch.
 * @param {string} dir
 * @param {number} issueNumber
 * @returns {$CancellablePromise<void>}
 */
export function RemoveWorktree(dir, issueNumber) {
    return $Call.ByID(375711242, dir, issueNumber);
}

/**
 * ResizeSession updates the PTY and screen buffer dimensions.
 * @param {number} id
 * @param {number} rows
 * @param {number} cols
 * @returns {$CancellablePromise<void>}
 */
export function ResizeSession(id, rows, cols) {
    return $Call.ByID(3357609161, id, rows, cols);
}

/**
 * SaveConfig saves the given config to disk and updates the in-memory copy.
 * @param {config$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(2393674620, cfg);
}

/**
 * SaveTabs persists the current tab/pane layout to disk so it can be
 * restored on next startup.
 * @param {config$0.SessionState} state
 * @returns {$CancellablePromise<void>}
 */
export function SaveTabs(state) {
    return $Call.ByID(3270785638, state);
}

/**
 * SaveWindowTabs is called by a secondary window whenever its tab store changes.
 * The state is persisted in the window entry so the backend can emit
 * window:tabs-merged reliably when the window closes (no IPC race).
 * @param {string} windowID
 * @param {string} tabStateJSON
 * @returns {$CancellablePromise<void>}
 */
export function SaveWindowTabs(windowID, tabStateJSON) {
    return $Call.ByID(1191563946, windowID, tabStateJSON);
}

/**
 * SearchFiles searches for files matching a query string in the given directory.
 * @param {string} dir
 * @param {string} query
 * @returns {$CancellablePromise<$models.FileEntry[]>}
 */
export function SearchFiles(dir, query) {
    return $Call.ByID(4086168286, dir, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * SelectDirectory opens a native directory picker dialog and returns the
 * selected path, or an empty string if the user cancelled.
 * @param {string} startDir
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(startDir) {
    return $Call.ByID(1609319006, startDir);
}

/**
 * SendNotification shows a native Windows toast notification with
 * "Multiterminal" as the application name. Clicking it brings the
 * window to the foreground via the multiterminal: custom protocol.
 * @param {string} title
 * @param {string} body
 * @returns {$CancellablePromise<void>}
 */
export function SendNotification(title, body) {
    return $Call.ByID(855829018, title, body);
}

/**
 * SetDraggingTab is called by the source window when a tab drag begins.
 * @param {string} tabID
 * @param {string} windowID
 * @param {string} tabStateJSON
 * @returns {$CancellablePromise<void>}
 */
export function SetDraggingTab(tabID, windowID, tabStateJSON) {
    return $Call.ByID(3912872371, tabID, windowID, tabStateJSON);
}

/**
 * SetMainWindow stores the main window reference for dialog and focus operations.
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(w) {
    return $Call.ByID(601784332, w);
}

/**
 * UpdateIssue updates an existing issue's title, body, and/or state.
 * @param {string} dir
 * @param {number} $number
 * @param {string} title
 * @param {string} body
 * @param {string} state
 * @returns {$CancellablePromise<void>}
 */
export function UpdateIssue(dir, $number, title, body, state) {
    return $Call.ByID(3829405869, dir, $number, title, body, state);
}

/**
 * ValidateClaudePath checks whether the given path points to an executable.
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateClaudePath(path) {
    return $Call.ByID(688761244, path);
}

/**
 * WriteToSession sends raw input data (base64-encoded) to a session's PTY.
 * @param {number} id
 * @param {string} b64data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToSession(id, b64data) {
    return $Call.ByID(2058166105, id, b64data);
}

// Private type creation functions
const $$createType0 = $models.QueueItem.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $models.HealthInfo.createFrom;
const $$createType3 = $models.Issue.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.WorktreeInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.ClaudeDetectResult.createFrom;
const $$createType8 = config$0.Config.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $models.IssueDetail.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.IssueLabel.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($$createType3);
const $$createType16 = $models.MergeConflictInfo.createFrom;
const $$createType17 = $models.WindowInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($$createType0);
const $$createType20 = $models.IssueBranchInfo.createFrom;
const $$createType21 = $Create.Array($$createType5);
const $$createType22 = $models.FileEntry.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = config$0.SessionState.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $models.FileContent.createFrom;
