// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClaudeDetectResult describes the outcome of a Claude CLI detection attempt.
 */
export class ClaudeDetectResult {
    /**
     * Creates a new ClaudeDetectResult instance.
     * @param {Partial<ClaudeDetectResult>} [$$source = {}] - The source object to create the ClaudeDetectResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "config", "path", "search", "manual"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeDetectResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeDetectResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeDetectResult(/** @type {Partial<ClaudeDetectResult>} */($$parsedSource));
    }
}

/**
 * FileContent holds the result of reading a file for preview.
 */
export class FileContent {
    /**
     * Creates a new FileContent instance.
     * @param {Partial<FileContent>} [$$source = {}] - The source object to create the FileContent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("binary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileContent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent(/** @type {Partial<FileContent>} */($$parsedSource));
    }
}

/**
 * FileEntry represents a file or directory in the sidebar.
 */
export class FileEntry {
    /**
     * Creates a new FileEntry instance.
     * @param {Partial<FileEntry>} [$$source = {}] - The source object to create the FileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry(/** @type {Partial<FileEntry>} */($$parsedSource));
    }
}

/**
 * HealthInfo is returned to the frontend on startup to indicate
 * whether crash-based logging should be suggested.
 */
export class HealthInfo {
    /**
     * Creates a new HealthInfo instance.
     * @param {Partial<HealthInfo>} [$$source = {}] - The source object to create the HealthInfo.
     */
    constructor($$source = {}) {
        if (!("crash_detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["crash_detected"] = false;
        }
        if (!("logging_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["logging_enabled"] = false;
        }
        if (!("logging_auto" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["logging_auto"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HealthInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthInfo(/** @type {Partial<HealthInfo>} */($$parsedSource));
    }
}

/**
 * Issue represents a GitHub issue summary for list views.
 */
export class Issue {
    /**
     * Creates a new Issue instance.
     * @param {Partial<Issue>} [$$source = {}] - The source object to create the Issue.
     */
    constructor($$source = {}) {
        if (!("number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("labels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["labels"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("comments" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["comments"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Issue}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField4_0($$parsedSource["labels"]);
        }
        return new Issue(/** @type {Partial<Issue>} */($$parsedSource));
    }
}

/**
 * IssueBranchInfo describes whether the current branch is an issue branch.
 */
export class IssueBranchInfo {
    /**
     * Creates a new IssueBranchInfo instance.
     * @param {Partial<IssueBranchInfo>} [$$source = {}] - The source object to create the IssueBranchInfo.
     */
    constructor($$source = {}) {
        if (!("on_issue_branch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_issue_branch"] = false;
        }
        if (!("branch_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch_name"] = "";
        }
        if (!("issue_number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["issue_number"] = 0;
        }
        if (!("is_same_issue" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_same_issue"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueBranchInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IssueBranchInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IssueBranchInfo(/** @type {Partial<IssueBranchInfo>} */($$parsedSource));
    }
}

/**
 * IssueComment represents a single comment on a GitHub issue.
 */
export class IssueComment {
    /**
     * Creates a new IssueComment instance.
     * @param {Partial<IssueComment>} [$$source = {}] - The source object to create the IssueComment.
     */
    constructor($$source = {}) {
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueComment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IssueComment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IssueComment(/** @type {Partial<IssueComment>} */($$parsedSource));
    }
}

/**
 * IssueDetail represents a full GitHub issue with body and comments.
 */
export class IssueDetail {
    /**
     * Creates a new IssueDetail instance.
     * @param {Partial<IssueDetail>} [$$source = {}] - The source object to create the IssueDetail.
     */
    constructor($$source = {}) {
        if (!("number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("labels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["labels"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("assignees" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["assignees"] = [];
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("comments" in $$source)) {
            /**
             * @member
             * @type {IssueComment[]}
             */
            this["comments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IssueDetail}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField4_0($$parsedSource["labels"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField8_0($$parsedSource["assignees"]);
        }
        if ("comments" in $$parsedSource) {
            $$parsedSource["comments"] = $$createField10_0($$parsedSource["comments"]);
        }
        return new IssueDetail(/** @type {Partial<IssueDetail>} */($$parsedSource));
    }
}

/**
 * IssueLabel represents a GitHub label with name and color.
 */
export class IssueLabel {
    /**
     * Creates a new IssueLabel instance.
     * @param {Partial<IssueLabel>} [$$source = {}] - The source object to create the IssueLabel.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IssueLabel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IssueLabel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IssueLabel(/** @type {Partial<IssueLabel>} */($$parsedSource));
    }
}

/**
 * MergeConflictInfo holds information about current merge conflicts.
 */
export class MergeConflictInfo {
    /**
     * Creates a new MergeConflictInfo instance.
     * @param {Partial<MergeConflictInfo>} [$$source = {}] - The source object to create the MergeConflictInfo.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["files"] = [];
        }
        if (!("operation" in $$source)) {
            /**
             * "merge", "rebase", "cherry-pick", ""
             * @member
             * @type {string}
             */
            this["operation"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeConflictInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeConflictInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new MergeConflictInfo(/** @type {Partial<MergeConflictInfo>} */($$parsedSource));
    }
}

/**
 * QueueItem represents a single prompt in a session's pipeline queue.
 */
export class QueueItem {
    /**
     * Creates a new QueueItem instance.
     * @param {Partial<QueueItem>} [$$source = {}] - The source object to create the QueueItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "pending", "sent", "done"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueueItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueItem(/** @type {Partial<QueueItem>} */($$parsedSource));
    }
}

/**
 * UpdateInfo holds the result of a GitHub release check.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }
        if (!("downloadURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * WindowInfo is returned to the frontend.
 */
export class WindowInfo {
    /**
     * Creates a new WindowInfo instance.
     * @param {Partial<WindowInfo>} [$$source = {}] - The source object to create the WindowInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tabIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tabIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabIds" in $$parsedSource) {
            $$parsedSource["tabIds"] = $$createField1_0($$parsedSource["tabIds"]);
        }
        return new WindowInfo(/** @type {Partial<WindowInfo>} */($$parsedSource));
    }
}

/**
 * WorktreeInfo describes an active git worktree.
 */
export class WorktreeInfo {
    /**
     * Creates a new WorktreeInfo instance.
     * @param {Partial<WorktreeInfo>} [$$source = {}] - The source object to create the WorktreeInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("issue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["issue"] = 0;
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktreeInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorktreeInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktreeInfo(/** @type {Partial<WorktreeInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = IssueComment.createFrom;
const $$createType2 = $Create.Array($$createType1);
