package skills

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	markerBegin = "<!-- MTUI:SKILLS:BEGIN — Auto-generated by Multiterminal, do not edit manually -->"
	markerEnd   = "<!-- MTUI:SKILLS:END -->"
	mtuiDir     = ".mtui"
	skillsFile  = "skills.json"
	skillsMD    = "skills.md"
	claudeMD    = "CLAUDE.md"
)

// SkillSelection tracks which skills are active for a project.
type SkillSelection struct {
	ActiveSkills []string `json:"active_skills" yaml:"active_skills"`
	UpdatedAt    string   `json:"updated_at" yaml:"updated_at"`
}

// InitMTUIDir creates the .mtui directory if it doesn't exist.
func InitMTUIDir(dir string) error {
	mtuiPath := filepath.Join(dir, mtuiDir)
	return os.MkdirAll(mtuiPath, 0755)
}

// IsMTUIProject checks if a directory has been initialized as an MTUI project.
func IsMTUIProject(dir string) bool {
	info, err := os.Stat(filepath.Join(dir, mtuiDir))
	return err == nil && info.IsDir()
}

// SaveSkillSelection persists the skill selection to .mtui/skills.json.
func SaveSkillSelection(dir string, skillIDs []string) error {
	if err := InitMTUIDir(dir); err != nil {
		return err
	}
	sel := SkillSelection{
		ActiveSkills: skillIDs,
		UpdatedAt:    time.Now().UTC().Format(time.RFC3339),
	}
	data, err := json.MarshalIndent(sel, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, mtuiDir, skillsFile), data, 0644)
}

// LoadSkillSelection reads the active skills from .mtui/skills.json.
func LoadSkillSelection(dir string) (*SkillSelection, error) {
	data, err := os.ReadFile(filepath.Join(dir, mtuiDir, skillsFile))
	if err != nil {
		return nil, err
	}
	var sel SkillSelection
	if err := json.Unmarshal(data, &sel); err != nil {
		return nil, err
	}
	return &sel, nil
}

// InjectIntoCLAUDEMD injects skill content into the project's CLAUDE.md.
// Also writes the full skill content to .mtui/skills.md as backup.
func InjectIntoCLAUDEMD(dir string, skillIDs []string) error {
	skills := GetSkills(skillIDs)
	if len(skills) == 0 {
		return nil
	}

	// Build the skills block
	block := buildSkillsBlock(skills)

	// Write backup to .mtui/skills.md
	if err := InitMTUIDir(dir); err != nil {
		return err
	}
	mdPath := filepath.Join(dir, mtuiDir, skillsMD)
	if err := os.WriteFile(mdPath, []byte(block), 0644); err != nil {
		return fmt.Errorf("writing skills.md: %w", err)
	}

	// Inject into CLAUDE.md
	claudePath := filepath.Join(dir, claudeMD)
	return injectBlock(claudePath, block)
}

// RemoveFromCLAUDEMD removes the skills block from CLAUDE.md.
func RemoveFromCLAUDEMD(dir string) error {
	claudePath := filepath.Join(dir, claudeMD)
	content, err := os.ReadFile(claudePath)
	if err != nil {
		return nil // no CLAUDE.md, nothing to remove
	}
	cleaned := removeBlock(string(content))
	return os.WriteFile(claudePath, []byte(cleaned), 0644)
}

// buildSkillsBlock creates the markdown block for injection.
func buildSkillsBlock(skills []Skill) string {
	var sb strings.Builder
	sb.WriteString(markerBegin)
	sb.WriteString("\n## Projekt-Skills\n\n")
	for i, s := range skills {
		sb.WriteString("### ")
		sb.WriteString(s.Name)
		sb.WriteString("\n")
		sb.WriteString(s.Content)
		sb.WriteString("\n")
		if i < len(skills)-1 {
			sb.WriteString("\n")
		}
	}
	sb.WriteString(markerEnd)
	sb.WriteString("\n")
	return sb.String()
}

// injectBlock inserts or replaces the skills block in a CLAUDE.md file.
func injectBlock(path, block string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		// No CLAUDE.md exists — create it with just the block
		return os.WriteFile(path, []byte(block+"\n"), 0644)
	}

	text := string(content)

	// If markers exist, replace the block
	if strings.Contains(text, markerBegin) {
		cleaned := removeBlock(text)
		// Insert at the position where the old block was
		result := block + "\n" + strings.TrimLeft(cleaned, "\n")
		return os.WriteFile(path, []byte(result), 0644)
	}

	// No markers — prepend the block
	result := block + "\n" + text
	return os.WriteFile(path, []byte(result), 0644)
}

// removeBlock strips the skills block (between markers) from content.
func removeBlock(content string) string {
	beginIdx := strings.Index(content, markerBegin)
	if beginIdx < 0 {
		return content
	}
	endIdx := strings.Index(content, markerEnd)
	if endIdx < 0 {
		return content
	}
	endIdx += len(markerEnd)
	// Also remove trailing newline after end marker
	if endIdx < len(content) && content[endIdx] == '\n' {
		endIdx++
	}
	return content[:beginIdx] + content[endIdx:]
}
